# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-07 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timestamp', '0003_projecttask'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimestampTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('desc', models.CharField(max_length=128)),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name': 'Отметка',
                'verbose_name_plural': 'Отметки',
            },
        ),
    ]
