# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-13 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timestamp', '0004_timestamptask'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttask',
            name='end',
            field=models.DateField(blank=True, default='2017-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projecttask',
            name='start',
            field=models.DateField(blank=True, default='2017-01-09'),
            preserve_default=False,
        ),
    ]
