# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-13 15:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timestamp', '0005_auto_20180113_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='timestamptask',
            name='task',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='timestamp.ProjectTask'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timestamptask',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='start',
            field=models.DateField(),
        ),
    ]
