# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-14 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timestamp', '0007_auto_20180114_0035'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Группа постоянныех работ',
                'verbose_name_plural': 'Группы постоянныех работ',
            },
        ),
        migrations.CreateModel(
            name='CommonTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timestamp.CommonStage')),
            ],
            options={
                'verbose_name': 'Постоянная работа',
                'verbose_name_plural': 'Постоянные работы',
            },
        ),
        migrations.AlterModelOptions(
            name='projecttask',
            options={'verbose_name': 'Проектная задача', 'verbose_name_plural': 'Проектные задачи'},
        ),
        migrations.AlterModelOptions(
            name='timestampstatus',
            options={'verbose_name': 'Статус отметок', 'verbose_name_plural': 'Статусы отметок'},
        ),
    ]
