# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-14 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timestamp', '0009_auto_20180114_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Тип задачи',
                'verbose_name_plural': 'Типы задач',
            },
        ),
        migrations.RemoveField(
            model_name='timestamptask',
            name='task',
        ),
        migrations.AddField(
            model_name='timestamptask',
            name='task_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projecttask',
            name='task_type',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='timestamp.TaskType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timestamptask',
            name='task_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='timestamp.TaskType'),
            preserve_default=False,
        ),
    ]
