# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-14 19:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timestamp', '0011_commontask_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='quartaltask',
            name='task_type',
            field=models.ForeignKey(blank=True, default=3, on_delete=django.db.models.deletion.CASCADE, to='timestamp.TaskType'),
            preserve_default=False,
        ),
    ]
